# Generated by Django 4.2.20 on 2025-03-16 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField()),
                ('outside_Europe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('manufacturer', models.CharField(max_length=100)),
                ('max_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('year_of_birth', models.IntegerField()),
                ('flight_hours', models.IntegerField()),
                ('rank', models.CharField(choices=[('J', 'Junior'), ('I', 'Intermediate'), ('S', 'Senior')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('take_off_airport', models.CharField(max_length=100)),
                ('land_off_airport', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flight_images/')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.airline')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.balloon')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.pilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirlinePilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.pilot')),
            ],
        ),
    ]
