# Generated by Django 4.2.20 on 2025-03-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='sold_product',
        ),
    ]
