# Generated by Django 4.2.20 on 2025-03-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_service_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='customer',
            new_name='user',
        ),
    ]
